'use client';

import Link from 'next/link';

export default function PrivacyPolicy() {
  return (
    <div className="container-privacy-policy">
      <h1 className="title">Privacy Policy</h1>
      <p className="text">
        This privacy policy applies to the SimiJuegos app (&quot;Application&quot;) for mobile devices that was created by
        Farmacias de Similares S.A. de C.V. (&quot;Service Provider&quot;) as a Free service. This service is intended for use
        &quot;AS IS&quot;.
      </p>
      
      <h2 className="subtitle">Information Collection and Use</h2>
      <p className="text">The Application collects information when you download and use it, including:</p>
      <ul className="list">
        <li>Your device&apos;s Internet Protocol address (IP address)</li>
        <li>The pages of the Application that you visit, the time and date of your visit, the time spent on those pages</li>
        <li>The time spent on the Application</li>
        <li>The operating system you use on your mobile device</li>
      </ul>
      <p className="text">The Application does not gather precise location information of your mobile device.</p>
      
      <h2 className="subtitle">Third Party Access</h2>
      <p className="text">
        Only aggregated, anonymized data is periodically transmitted to external services to aid the Service Provider
        in improving the Application. The Application utilizes third-party services with their own Privacy Policy.
      </p>
      <p className="text">Below is a link to the Privacy Policy of the third-party service provider used by the Application:</p>
      <ul className="list">
        <li>
          <Link href="https://www.google.com/policies/privacy/" target="_blank" rel="noopener noreferrer" className="link">
            Google Play Services
          </Link>
        </li>
      </ul>
      
      <h2 className="subtitle">Opt-Out Rights</h2>
      <p className="text">You can stop all collection of information by the Application by uninstalling it.</p>
      
      <h2 className="subtitle">Data Retention Policy</h2>
      <p className="text">
        The Service Provider will retain User Provided data for as long as you use the Application and for a reasonable
        time thereafter. To delete your data, contact <a href="mailto:bryan@aroundthelab.com" className="link">bryan@aroundthelab.com</a>.
      </p>
      
      <h2 className="subtitle">Children</h2>
      <p className="text">
        The Service Provider does not knowingly collect personally identifiable information from children under 13.
        If a child has provided personal information, contact <a href="mailto:bryan@aroundthelab.com" className="link">bryan@aroundthelab.com</a> to remove it.
      </p>
      
      <h2 className="subtitle">Security</h2>
      <p className="text">The Service Provider safeguards your information using physical, electronic, and procedural security measures.</p>
      
      <h2 className="subtitle">Changes</h2>
      <p className="text">
        This Privacy Policy may be updated from time to time. Updates will be posted on this page.
      </p>
      <p className="effectiveDate">Effective date: 2025-02-28</p>
      
      <h2 className="subtitle">Your Consent</h2>
      <p className="text">By using the Application, you consent to this Privacy Policy.</p>
      
      <h2 className="subtitle">Contact Us</h2>
      <p className="text">
        If you have any questions about this Privacy Policy, contact us at{' '}
        <a href="mailto:bryan@aroundthelab.com" className="link">bryan@aroundthelab.com</a>.
      </p>
      
      <hr className="separator" />
      <p className="footerText">
        This privacy policy page was generated by{' '}
        <Link href="https://app-privacy-policy-generator.nisrulz.com/" target="_blank" rel="noopener noreferrer" className="link">
          App Privacy Policy Generator
        </Link>
      </p>
    </div>
  );
}