export const LOCAL_STORAGE_KEYS = {
  IS_GUEST: "IS_GUEST",
  GUEST_SCORE: "GUEST_SCORE",
  GUEST_GAMES_PLAYED: "GUEST_GAMES_PLAYED",
  GUEST_GAMES: "GUEST_GAMES",
  LAST_GUEST_LOGIN_TIME: "LAST_GUEST_LOGIN_TIME",
};